streamlit run interact.py 0 "Feeling nervous about my presentation"
streamlit run interact.py 1 "Feeling nervous about my presentation"
streamlit run interact.py 2 "Feeling nervous about my presentation"
streamlit run interact.py 3 "Feeling nervous about my presentation"
streamlit run interact.py 4 "Feeling nervous about my presentation"
streamlit run interact.py 5 "Feeling nervous about my presentation"