wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    framework: huggingface
    huggingface_version: 4.27.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.12
    start_time: 1706414398
    t:
      1:
      - 1
      - 5
      - 11
      - 33
      - 49
      - 51
      - 53
      - 55
      - 71
      3:
      - 16
      4: 3.10.12
      5: 0.12.21
      6: 4.27.1
      8:
      - 5
adam_epsilon:
  desc: null
  value: 1.0e-08
add_emo_cross_attn:
  desc: null
  value: false
attend_eos:
  desc: null
  value: false
base_vocab_size:
  desc: null
  value: 50265
block_size:
  desc: null
  value: 512
data_cache_dir:
  desc: null
  value: /disk/junlin/EmoSp/124_II_noprep_bart__emin_w_situw_vadcached
data_path:
  desc: null
  value: converted_dataset
device:
  desc: null
  value: cuda
do_train:
  desc: null
  value: true
emo_from_eos:
  desc: null
  value: true
emo_from_situ:
  desc: null
  value: false
emo_loss_ratio:
  desc: null
  value: 0.2
emo_out_loss_ratio:
  desc: null
  value: 0.2
emo_use_cat_attn:
  desc: null
  value: true
eval_comet_file:
  desc: null
  value: devComet.txt
eval_file_name:
  desc: null
  value: devWithStrategy_short.tsv
evaluate_during_training:
  desc: null
  value: true
fp16:
  desc: null
  value: false
fp16_opt_level:
  desc: null
  value: O1
freeze_emo_stag_params:
  desc: null
  value: true
generation_dir:
  desc: null
  value: our_generated_data/-LIGHT-TRANS4/all_loss0.6_0.2_0.2_kl-lr_2e-05-Situ-Emoin-nopp-empp-no_fuse-bart-eosemo-role-emocat-stgcat-vae-mvae256-wo_comet-vad-frz_stem124_II
gradient_accumulation_steps:
  desc: null
  value: 1
intensity_vae:
  desc: null
  value: false
latent_dim:
  desc: null
  value: 256
learning_rate:
  desc: null
  value: 2.0e-05
local_rank:
  desc: null
  value: -1
logging_steps:
  desc: null
  value: 200
lstm_st_seq:
  desc: null
  value: false
max_grad_norm:
  desc: null
  value: 1.0
max_steps:
  desc: null
  value: -1
merge:
  desc: null
  value: false
mixed_vae:
  desc: null
  value: true
model_cache_dir:
  desc: null
  value: ./blender-small
model_name_or_path:
  desc: null
  value: facebook/bart-base
model_type:
  desc: null
  value: mymodel
n_gpu:
  desc: null
  value: 1
no_cuda:
  desc: null
  value: false
no_fuse:
  desc: null
  value: true
num_train_epochs:
  desc: null
  value: 10
output_dir:
  desc: null
  value: /disk/junlin/EmoSp/bart-our/-LIGHT-TRANS4/all_loss0.6_0.2_0.2_kl-lr_2e-05-Situ-Emoin-nopp-empp-no_fuse-bart-eosemo-role-emocat-stgcat-vae-mvae256-wo_comet-vad-frz_stem124_II
overwrite_cache:
  desc: null
  value: false
per_gpu_eval_batch_size:
  desc: null
  value: 20
per_gpu_train_batch_size:
  desc: null
  value: 20
prepend_emotion:
  desc: null
  value: false
rl_emb_ratio:
  desc: null
  value: 0.6
role:
  desc: null
  value: false
sample_strat_emb:
  desc: null
  value: false
save_total_limit:
  desc: null
  value: 1
seed:
  desc: null
  value: 42
situation_eval_comet_file:
  desc: null
  value: devComet_st.txt
situation_eval_file:
  desc: null
  value: devSituation.txt
situation_test_comet_file:
  desc: null
  value: testComet_st.txt
situation_test_file:
  desc: null
  value: testSituation.txt
situation_train_comet_file:
  desc: null
  value: trainComet_st.txt
situation_train_file:
  desc: null
  value: trainSituation.txt
st_from_eos:
  desc: null
  value: true
stg_use_cat_attn:
  desc: null
  value: true
strategy:
  desc: null
  value: false
test_comet_file:
  desc: null
  value: testComet.txt
test_file_name:
  desc: null
  value: testWithStrategy_short.tsv
train_comet_file:
  desc: null
  value: trainComet.txt
train_file_name:
  desc: null
  value: trainWithStrategy_short.tsv
turn:
  desc: null
  value: false
use_bart:
  desc: null
  value: true
use_copy:
  desc: null
  value: false
use_emb_prep:
  desc: null
  value: true
use_emo_in_dist:
  desc: null
  value: true
use_kl:
  desc: null
  value: true
use_role_embed:
  desc: null
  value: true
use_situ:
  desc: null
  value: true
use_st_seq:
  desc: null
  value: false
use_th_attn:
  desc: null
  value: false
use_trans_mat:
  desc: null
  value: true
use_vad_labels:
  desc: null
  value: true
use_vae:
  desc: null
  value: true
vad_emb_ratio:
  desc: null
  value: 0.2
warmup_steps:
  desc: null
  value: 200
weight_decay:
  desc: null
  value: 0
wo_comet:
  desc: null
  value: true
wo_emo:
  desc: null
  value: false
wo_stra:
  desc: null
  value: false
